on:
  - push

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        #os: [ubuntu-20.04, ubuntu-22.04]
        racket-variant: ['BC'] #, 'CS']
        racket-version: ['8.6'] #, '8.8', '8.14']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install WSL
        uses: Vampire/setup-wsl@v3
      - name: Install nasm
        shell: wsl-bash
        run: sudo apt-get install nasm
      - name: Install Racket
        shell: wsl-bash
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Version info
        run: |
          nasm --version
          gcc --version      
