on:
  - push

jobs:
  build-and-test:
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    strategy:
      matrix:
        #os: [ubuntu-20.04, ubuntu-22.04]
        racket-variant: ['BC'] #, 'CS']
        racket-version: ['8.6'] #, '8.8', '8.14']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install WSL
        uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-24.04
#      - name: Apt update # Necessary before any sudo apt-get steps on WSL
#        run: sudo apt update 
#     - name: Install GCC
#        run: sudo apt-get install gcc -y
#      - name: Install nasm
#        run: sudo apt-get install nasm
      - name: Install Racket
        run: bash src/install-racket.sh ${{ matrix.racket-variant }} ${{ matrix.racket-version }} # TODO: pass in configuration
      - name: Hello world
        run: ./racket/bin/racket src/hello-world.rkt
      - name: Version info
        run: |
          racket --version
          nasm --version
          gcc --version      
          racket --version
