on:
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest]
          racket-variant: ['BC'] #, 'CS']
          racket-version: ['8.6'] #, '8.8', '8.14']
    defaults:
      run:
        shell: wsl-bash {0}
    name: Clone in wsl
    steps:
      - name: Install WSL
        uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-24.04
      - name: Copy the github repo
        run: |
          echo "$GITHUB_REPOSITORY"
          cp -r ${{ github.repository }} ~/langs/

        # https://github.com/ubuntu/WSL/blob/main/.github/workflows/wsl-example.yaml
        # https://github.com/ubuntu/WSL/blob/main/docs/reference/actions.md
        # alternative: try to install the pkg from OR move the repo from {{ github.repository }} to WSL