on:
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest]
          racket-variant: ['BC'] #, 'CS']
          racket-version: ['8.6'] #, '8.8', '8.14']
    defaults:
      run:
        shell: wsl-bash {0}
    name: Clone in wsl
    steps:
      - name: Install WSL
        uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-24.04
      # https://github.com/desktop/desktop/issues/17149
      # https://github.com/actions/checkout/discussions/976
      - name: Fool git
        shell: pwsh # This is the only run command that runs directly on windows powershell
        run: |
          git config --global core.protectNTFS false  
      - name: Fool git in bash too
        run: |
          git config --global core.protectNTFS false  
      - name: Checkout
        uses: actions/checkout@v2


        # https://github.com/ubuntu/WSL/blob/main/.github/workflows/wsl-example.yaml
        # https://github.com/ubuntu/WSL/blob/main/docs/reference/actions.md
        # alternative: try to install the pkg from OR move the repo from {{ github.repository }} to WSL