on:
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        racket-variant: ['BC'] #, 'CS']
        racket-version: ['8.6'] #, '8.8', '8.14']
    defaults:
      run:
        shell: wsl-bash {0}
    name: Test on Racket ${{ matrix.racket-variant }} ${{ matrix.racket-version }} on ${{ matrix.os }}	
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install WSL
        uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-24.04
      - name: Apt update # Necessary before any sudo apt-get steps on WSL
        run: sudo apt update 
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Install GCC
        run: sudo apt-get install gcc -y
      - name: Install nasm
        run: sudo apt-get install nasm
      - name: Install Racket
        run: bash .github/workflows/wsl-install-rkt.sh ${{ matrix.racket-variant }} ${{ matrix.racket-version }}
      - name: Version info
        run: |
          ~/racket/bin/racket --version
          nasm --version
          gcc --version      
      - name: Install langs package
        run: |
          ~/racket/bin/raco pkg install --auto ../actions-tst/ # TODO: test in my repo
      - name: Run tests
        run: |
          xvfb-run raco test -p langs
